### PR TITLE
Update amazonec2.py to fix variable region reference before assigment

### PR DESCRIPTION
**Pull request by thimslugga**
Update amazonec2.py to fix variable region reference before assigment i.e. `UnboundLocalError: local variable 'region' referenced before assignment`. This issue affects SLES based instances in the AWS GovCloud regions.

```
ip-172-31-30-71:~ # zypper up cloud-regionsrv-client \
>   cloud-regionsrv-client-plugin-ec2 \
>   regionServiceClientConfigEC2 \
>   python3-ec2metadata \
>   SUSEConnect

The following 11 items are locked and will not be changed by any action:
 Available:
  plymouth plymouth-branding-SLE plymouth-devel plymouth-dracut plymouth-plugin-label plymouth-plugin-label-ft plymouth-plugin-script plymouth-plugin-tribar plymouth-scripts plymouth-theme-tribar plymouth-x11-renderer

The following 2 packages are going to be upgraded:
  cloud-regionsrv-client cloud-regionsrv-client-plugin-ec2

2 packages to upgrade.
Overall download size: 102.3 KiB. Already cached: 0 B. After the operation, additional 4.5 KiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package cloud-regionsrv-client-10.1.5-52.102.1.noarch                                                                                                                                                                    (1/2),  76.8 KiB (177.3 KiB unpacked)
Retrieving: cloud-regionsrv-client-10.1.5-52.102.1.noarch.rpm .....................................................................................................................................................................................................[done]
Retrieving package cloud-regionsrv-client-plugin-ec2-1.0.3-52.102.1.noarch                                                                                                                                                          (2/2),  25.5 KiB (  3.6 KiB unpacked)
Retrieving: cloud-regionsrv-client-plugin-ec2-1.0.3-52.102.1.noarch.rpm ...........................................................................................................................................................................................[done]

Checking for file conflicts: ......................................................................................................................................................................................................................................[done]
(1/2) Installing: cloud-regionsrv-client-10.1.5-52.102.1.noarch ...................................................................................................................................................................................................[done]
(2/2) Installing: cloud-regionsrv-client-plugin-ec2-1.0.3-52.102.1.noarch .........................................................................................................................................................................................[done]

ip-172-31-30-71:~ # SUSEConnect -s
[{"identifier":"SLES","version":"12.5","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-adv-systems-management","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-containers","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-hpc","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-legacy","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-public-cloud","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-toolchain","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-web-scripting","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-sdk","version":"12.5","arch":"x86_64","status":"Registered"}]

# python errors regarding 'region' variable 

ip-172-31-30-71:~ # registercloudguest --force-new
Traceback (most recent call last):
  File "/usr/sbin/registercloudguest", line 277, in <module>
    utils.write_framework_identifier(cfg)
  File "/usr/lib/python3.4/site-packages/cloudregister/registerutils.py", line 1402, in write_framework_identifier
    region_hint = __get_region_server_args(plugin)
  File "/usr/lib/python3.4/site-packages/cloudregister/registerutils.py", line 1461, in __get_region_server_args
    region_srv_args = plugin.generateRegionSrvArgs()
  File "/usr/lib/python3.4/site-packages/cloudregister/amazonec2.py", line 98, in generateRegionSrvArgs
    return 'regionHint=' + region
UnboundLocalError: local variable 'region' referenced before assignment

# Check again

ip-172-31-30-71:~ # SUSEConnect -s
[{"identifier":"SLES","version":"12.5","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-adv-systems-management","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-containers","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-hpc","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-legacy","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-public-cloud","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-toolchain","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-module-web-scripting","version":"12","arch":"x86_64","status":"Not Registered"},{"identifier":"sle-sdk","version":"12.5","arch":"x86_64","status":"Not Registered"}]
```

```
ip-172-31-30-71:~ # rpm -ql cloud-regionsrv-client-plugin-ec2
/usr/lib/python3.4/site-packages/cloudregister/amazonec2.py

ip-172-31-30-71:~ # vim /usr/lib/python3.4/site-packages/cloudregister/amazonec2.py
```

After implementing fix:

```
ip-172-31-30-71:~ # registercloudguest --force-new
Registration succeeded

ip-172-31-30-71:~ # SUSEConnect -s
[{"identifier":"SLES","version":"12.5","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-adv-systems-management","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-containers","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-hpc","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-legacy","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-public-cloud","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-toolchain","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-module-web-scripting","version":"12","arch":"x86_64","status":"Registered"},{"identifier":"sle-sdk","version":"12.5","arch":"x86_64","status":"Registered"}]
```

### CODE REVIEW

**Comment by rjschwei** [comment]
Can you please expand the test cases in `test_ec2plugin.py` to include other region identifiers, i.e. `us-gov-east-1a` and a local zone identified for example by `us-east-1-bos-1a`. Also please update the preceding comment about the zone naming convention.  Last but not least the change is not correct as it does not properly identify the gov cloud region. Here is the example, the response from IMDS is simulated to be us-gov-west-1b:

```
>>> region_data = 'us-gov-west-1b'.split('-', 3)
>>> region_id_az = region_data[2]
>>> region_id = ''
>>> for c in region_id_az:
...     if c.isdigit():
...         region_id += c
... 
>>> region = '-'.join(region_data[:2] + [region_id])
>>> region
'us-gov-'
```
The proper value for `region` should be `us-gov-west-1`.

Yes the indentation is incorrect in the code, but that is not sufficient we also have to handle a 3 entry identifier as a prefix to the az identifier. The current implementation only handles a 2 entry prefix as indicated by the `split()` command by using the `3` as the maximum split length. I can pick it up via the bug report if you do not want to get that far into the weeds @thimslugga

**Review by rjschwei — CHANGES_REQUESTED** [review]
While the indentation is a bug, moving the statement to the left is not sufficient. See the longer explanation as general comment.

**Comment by reelieuglie** [comment]
This will likely need a bit of testing and adjusting; I have only tested it in a single ec2 instance. I'm sure you have the means to perform a bit more rigorous testing Robert, but I'll provide  this to keep the   ball rolling...it appears to work for govcloud:

```
zone_resp = 'us-gov-west-1'
region_data = zone_resp.split('-', 3)
if "gov" in region_data:
        x = 3
else:
        x = 2
region_id_az = region_data[x]
region_id = ''
for c in region_id_az:
    if c.isdigit():
            region_id += c
     region = '-'.join(region_data[:x] + [region_id])
     print(region)                                   
```
```
# python3 ./test.py 
us-gov-west-1

```
And then if I add this section to the `amazonec2.py ` file:
```
            region_data = zone_resp.text.split('-', 3)
	    if "gov" in region_data:
    		    x = 3
		else:
        	    x = 2
            region_id_az = region_data[x]
            region_id = ''
            for c in region_id_az:
                if c.isdigit():
                    region_id += c
            region = '-'.join(region_data[:x] + [region_id])
```
Registration succeeds:
```
ip-10-0-100-238:/home/ec2-user # vim /usr/lib/python3.4/site-packages/cloudregister/amazonec2.py
ip-10-0-100-238:/home/ec2-user # registercloudguest --clean
ip-10-0-100-238:/home/ec2-user # registercloudguest --force-new
Registration succeeded
```

I do not have the means to test this in a variety of situations; but registration still succeeds and the test snippet returns the `us-gov-west-1` region.

**Comment by rjschwei** [comment]
Superseded by #142

**Pull request closed without merging**
